Logger: 
  Level: 2
  ConsoleEncoder: true
Database:
  URL:
  Host: '127.0.0.1'
  Port: 5432
  Name: 'postgres'
  User: 'postgres'
  Pass: 'postgres'
  LogQueries: true
  Pool:
    LogConnectOperations: true
    MaxConnLifetime: 100ms
    # MaxConnLifetimeJitter:
    # MaxConnIdleTime:
    # MaxConns:
    # MinConns:
    # HealthCheckPeriod:

